# Generated by Django 5.0 on 2024-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="marketItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.CharField(max_length=20)),
                ("itemDescription", models.TextField(max_length=100)),
                ("itemPrice", models.IntegerField()),
                ("itemPic", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
