# Generated by Django 5.0 on 2024-02-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loginPage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField(max_length=2)),
                ("dob", models.DateField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loginPage.logincredential",
                    ),
                ),
            ],
        ),
    ]
